- AUTENTICACAO - 

CENTRO DE CUSTO - MENSAL

::CATEGORIAS
::DESPESAS 
CAMPOS: ID, NOME, DATA_VENCIMENTO, DATA_PAGAMENTO, FIXA, PARCELADAS
::RECEITAS (RENDAS, FIXA OU VARIÁVEL)
CAMPOS: ID, NOME, DATA_VENCIMENTO, DATA_PAGAMENTO, FIXA, PARCELADAS
::METAS (PLANOS E DESEJOS)
CAMPOS: ID, NOME, VALOR TOTAL, QUANTIDADE DE PARCELAS.
::CARTOES DE CREDITO
::BANCOS COM SALDOS
::PATRIMONIOS (CASA, CARRO, MOTO E ETC)
::SIMULADORES DE INVESTIMENTOS(CDB, LCI E ETC)
SIMULAR COM O SALDO EM CONTA, PARA DEIXAR O USUARIO
CIENTE DO QUE ELE RENDER.


